-- Ubiquitous Craft: database schema for Supabase (PostgreSQL).
-- Run this ONCE in Supabase: SQL Editor -> New query -> paste all -> Run.
-- It is safe to run again: tables use "if not exists", policies are dropped and recreated,
-- and the 8 default products are only inserted when their slug is missing.

-- =====================================================================
-- 1. Tables
-- =====================================================================

-- Adjustable limits. Change them any time, e.g.:
--   update public.settings set value = '25' where key = 'max_customers';
create table if not exists public.settings (
  key   text primary key,
  value jsonb not null
);

insert into public.settings (key, value) values
  ('max_customers', '10'),
  ('max_custom_products', '10')
on conflict (key) do nothing;

-- One row per signed-up user. The login itself (email + password) lives in Supabase Auth.
create table if not exists public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  display_name text not null,
  role         text not null default 'customer' check (role in ('customer', 'admin')),
  created_at   timestamptz not null default now()
);
create unique index if not exists profiles_display_name_key on public.profiles (lower(display_name));

create table if not exists public.products (
  id               bigint generated by default as identity primary key,
  slug             text not null unique,
  name             text not null check (char_length(name) between 1 and 60),
  price            numeric(10, 2) not null check (price >= 0 and price <= 10000),
  category         text not null check (category in ('Figurines', 'Home', 'Desk', 'Accessories')),
  color            text not null check (color ~ '^#[0-9a-fA-F]{6}$'),
  image            text not null,
  thumb            text not null,
  blurb            text not null default '' check (char_length(blurb) <= 100),
  description      text not null default '' check (char_length(description) <= 500),
  material         text not null default 'PLA' check (char_length(material) <= 40),
  print_time_hours numeric(6, 1) not null default 1 check (print_time_hours >= 0 and print_time_hours <= 500),
  custom           boolean not null default false,   -- true = added through the admin page
  created_at       timestamptz not null default now()
);

create table if not exists public.cart_items (
  user_id    uuid   not null default auth.uid() references auth.users (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade,
  qty        int    not null check (qty between 1 and 99),
  primary key (user_id, product_id)
);

-- =====================================================================
-- 2. Helper functions
-- =====================================================================

create or replace function public.is_admin()
returns boolean
language sql security definer stable
set search_path = ''
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

-- How many customer sign-up spots are left (used by the sign-up page).
create or replace function public.spots_left()
returns int
language sql security definer stable
set search_path = ''
as $$
  select greatest(
    0,
    coalesce((select (value #>> '{}')::int from public.settings where key = 'max_customers'), 10)
      - (select count(*) from public.profiles where role = 'customer')
  )::int;
$$;

-- Is this display name free? (used by the sign-up page before creating the account)
create or replace function public.display_name_available(name text)
returns boolean
language sql security definer stable
set search_path = ''
as $$
  select lower(btrim(name)) not in ('admin', 'administrator')
     and not exists (select 1 from public.profiles where lower(display_name) = lower(btrim(name)));
$$;

-- When someone signs up, create their profile and enforce the customer limit.
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer
set search_path = ''
as $$
declare
  dn text := btrim(coalesce(new.raw_user_meta_data ->> 'display_name', ''));
begin
  if dn !~ '^[A-Za-z0-9_]{3,20}$' then
    raise exception 'Display name must be 3-20 letters, numbers or underscores.';
  end if;
  if lower(dn) in ('admin', 'administrator') then
    raise exception 'That display name is reserved.';
  end if;
  if public.spots_left() <= 0 then
    raise exception 'Sign-up limit reached.';
  end if;
  insert into public.profiles (id, display_name) values (new.id, dn);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Limit how many products the admin can add.
create or replace function public.enforce_product_cap()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  cap int := coalesce((select (value #>> '{}')::int from public.settings where key = 'max_custom_products'), 10);
begin
  if new.custom and (select count(*) from public.products where custom) >= cap then
    raise exception 'Product limit reached (%). Delete one to add another.', cap;
  end if;
  return new;
end;
$$;

drop trigger if exists products_cap on public.products;
create trigger products_cap
  before insert on public.products
  for each row execute function public.enforce_product_cap();

revoke all on function public.is_admin(), public.spots_left(), public.display_name_available(text) from public;
grant execute on function public.is_admin(), public.spots_left(), public.display_name_available(text) to anon, authenticated;

-- =====================================================================
-- 3. Row Level Security (who may see / change what)
-- =====================================================================

alter table public.settings   enable row level security;
alter table public.profiles   enable row level security;
alter table public.products   enable row level security;
alter table public.cart_items enable row level security;

drop policy if exists "settings are public"     on public.settings;
drop policy if exists "read own profile"        on public.profiles;
drop policy if exists "products are public"     on public.products;
drop policy if exists "admin adds products"     on public.products;
drop policy if exists "admin edits products"    on public.products;
drop policy if exists "admin deletes products"  on public.products;
drop policy if exists "own cart"                on public.cart_items;

create policy "settings are public"    on public.settings for select using (true);
create policy "read own profile"       on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "products are public"    on public.products for select using (true);
create policy "admin adds products"    on public.products for insert to authenticated with check (public.is_admin());
create policy "admin edits products"   on public.products for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin deletes products" on public.products for delete to authenticated using (public.is_admin());
create policy "own cart"               on public.cart_items for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Table privileges (Row Level Security above narrows these further).
grant usage on schema public to anon, authenticated;
grant select on public.settings, public.products to anon, authenticated;
grant select on public.profiles to authenticated;
grant insert, update, delete on public.products to authenticated;
grant select, insert, update, delete on public.cart_items to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;

-- =====================================================================
-- 4. Photo storage for admin-added products
-- =====================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 2097152, array['image/jpeg'])
on conflict (id) do nothing;

drop policy if exists "product images admin read"   on storage.objects;
drop policy if exists "product images admin add"    on storage.objects;
drop policy if exists "product images admin edit"   on storage.objects;
drop policy if exists "product images admin delete" on storage.objects;

create policy "product images admin read"   on storage.objects for select to authenticated using (bucket_id = 'product-images' and public.is_admin());
create policy "product images admin add"    on storage.objects for insert to authenticated with check (bucket_id = 'product-images' and public.is_admin());
create policy "product images admin edit"   on storage.objects for update to authenticated using (bucket_id = 'product-images' and public.is_admin());
create policy "product images admin delete" on storage.objects for delete to authenticated using (bucket_id = 'product-images' and public.is_admin());

-- =====================================================================
-- 5. The 8 default products (inserted in this order, so ids 1-8; the first 4 are the home page picks)
-- =====================================================================

insert into public.products (slug, name, price, category, color, image, thumb, blurb, description, material, print_time_hours) values
  ('winged-dragon-figurine', 'Winged Dragon Figurine', 24, 'Figurines', '#FF6B6B',
   'images/products/winged-dragon-figurine.jpg', 'images/products/thumbs/winged-dragon-figurine.jpg',
   'A wings-out dragon on its own display base.',
   'A detailed dragon with a full wingspan, printed in one piece on its own round base. Finished in matte white so it looks great on a shelf or ready to paint.',
   'PLA+', 9),
  ('ripple-twist-vase', 'Ripple Twist Vase', 16, 'Home', '#4ECDC4',
   'images/products/ripple-twist-vase.jpg', 'images/products/thumbs/ripple-twist-vase.jpg',
   'A wavy, spiral-ribbed vase with a flared rim.',
   'Vase-mode printing gives this piece its smooth, flowing ribs and light-catching layer lines. Perfect for dried stems, pens, or just sitting pretty on a windowsill.',
   'PLA', 4),
  ('lucky-cat-mini-planter', 'Lucky Cat Mini Planter', 13, 'Home', '#FFD93D',
   'images/products/lucky-cat-mini-planter.jpg', 'images/products/thumbs/lucky-cat-mini-planter.jpg',
   'A beckoning lucky cat with grow-your-own moss ears.',
   'A textured, fur-detailed lucky cat figurine with hollow ears you can fill with moss or tiny plants. Brings a little good fortune to your desk.',
   'PLA', 5),
  ('honeycomb-trinket-dish', 'Honeycomb Trinket Dish', 12, 'Desk', '#FF9F45',
   'images/products/honeycomb-trinket-dish.jpg', 'images/products/thumbs/honeycomb-trinket-dish.jpg',
   'A hexagon dish for keys, clips and small things.',
   'A clean, sturdy hexagonal tray with tall walls. Line several up to build a honeycomb of desk storage for rings, paperclips, coins and keys.',
   'PETG', 3),
  ('piggy-coin-bank', 'Piggy Coin Bank', 15, 'Desk', '#F76E9C',
   'images/products/piggy-coin-bank.jpg', 'images/products/thumbs/piggy-coin-bank.jpg',
   'A round little piggy with a coin slot on top.',
   'A chubby piggy bank with floppy ears and a snout you''ll want to boop. The coin slot fits everything from pennies to quarters.',
   'PLA', 6),
  ('lil-elephant-figurine', 'Lil'' Elephant Figurine', 10, 'Figurines', '#6BCB77',
   'images/products/lil-elephant-figurine.jpg', 'images/products/thumbs/lil-elephant-figurine.jpg',
   'A cuddled-up elephant with a ridged trunk.',
   'A pocket-sized elephant curled up for a nap, printed in bright green. The ridged trunk is a small showcase of what fine layer heights can do.',
   'PLA', 2),
  ('bloom-drop-earrings', 'Bloom Drop Earrings', 14, 'Accessories', '#A66DD4',
   'images/products/bloom-drop-earrings.jpg', 'images/products/thumbs/bloom-drop-earrings.jpg',
   'Lightweight ribbed-bloom earrings in bold colors.',
   'Ribbed, lantern-style blooms in purple, black and red, hung on silver hooks. Featherlight, so you can wear them all day.',
   'Nylon', 2),
  ('twist-star-hoop-earrings', 'Twist Star Hoop Earrings', 9, 'Accessories', '#4D96FF',
   'images/products/twist-star-hoop-earrings.jpg', 'images/products/thumbs/twist-star-hoop-earrings.jpg',
   'Flowing star-shaped hoops in warm amber.',
   'A single continuous ribbon twisted into a star, printed in biodegradable PLA. Light, flexible, and a real conversation starter.',
   'PLA (biodegradable)', 1)
on conflict (slug) do nothing;

-- =====================================================================
-- To make YOUR account the admin (after you have signed up on the site), run:
--
--   update public.profiles set role = 'admin'
--   where id = (select id from auth.users where email = 'you@example.com');
--
-- Then log out and back in.
-- =====================================================================

-- =====================================================================
-- 6. Admin user management (same as 002-admin-users.sql)
-- =====================================================================

create or replace function public.admin_list_users()
returns table (user_id uuid, display_name text, email text, role text, created_at timestamptz)
language plpgsql security definer stable
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Admins only.';
  end if;
  return query
    select p.id, p.display_name, u.email::text, p.role, p.created_at
    from public.profiles p
    join auth.users u on u.id = p.id
    order by p.created_at, p.display_name;
end;
$$;

-- Deletes a customer's login. Their profile and saved cart go with it (on delete cascade).
create or replace function public.admin_delete_user(target uuid)
returns void
language plpgsql security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Admins only.';
  end if;
  if target = auth.uid() then
    raise exception 'You cannot delete your own account.';
  end if;
  if not exists (select 1 from public.profiles where id = target) then
    raise exception 'User not found.';
  end if;
  if exists (select 1 from public.profiles where id = target and role = 'admin') then
    raise exception 'Admin accounts cannot be deleted here.';
  end if;
  delete from auth.users where id = target;
end;
$$;

revoke all on function public.admin_list_users(), public.admin_delete_user(uuid) from public, anon;
grant execute on function public.admin_list_users(), public.admin_delete_user(uuid) to authenticated;
